###
http://localhost:3000/

### REG / LOG

###
POST http://localhost:3000/api/register
Content-Type: application/json

{
"nickname": "saulius",
"email": "saulius@lrt.lt",
"password": "secret123"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
"email": "saulius@lrt.lt",
"password": "secret123"
}

### BOOK get, add, update, delete

###
GET http://localhost:3000/api/book


###
POST http://localhost:3000/api/book
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY2NDQ2Nzc4NywiZXhwIjoxNjY0NDc4NTg3fQ.4zDELB5KdXoZNGJuFNPcT21FkbiOOsWEJLVyEXv1Yig

{
  "title": "Controller",
  "author": "Nezinomas informatikas",
  "publisher": "Ctrl leidykla",
  "publishing_date": "2022-09-01",
  "genre": "Istorija",
  "isbn": "54"
}

###
PATCH http://localhost:3000/api/book/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY2NDQ2Nzc4NywiZXhwIjoxNjY0NDc4NTg3fQ.4zDELB5KdXoZNGJuFNPcT21FkbiOOsWEJLVyEXv1Yig

{
  "title": "Controller moving",
  "author": "Nezinomas informatikas",
  "publisher": "Ctrl leidykla",
  "publishing_date": "2022-09-01",
  "genre": "Istorija",
  "isbn": "54"
}

###
DELETE http://localhost:3000/api/book/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY2NDQ2Nzc4NywiZXhwIjoxNjY0NDc4NTg3fQ.4zDELB5KdXoZNGJuFNPcT21FkbiOOsWEJLVyEXv1Yig

